# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tester.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

THEMES = {'Простейший поток': 0,
          'Суммирование и разъединение простейших потоков': 1,
          'Показательный закон распределения времени обслуживания': 2,
          'Нестационарный Пуассоновский поток': 3,
          'Теорема Литтла': 4,
          'Задачи для самостоятельного решения 1': 5,
          'Одноканальная система массового обслуживания с отказами': 6,
          'Система массового обслуживания с ожиданием и без ограничения очереди': 7,
          'Система массового обслуживания с ожиданием и ограничением длины очереди': 8,
          'Многоканальная система массового обслуживания с отказами М/М/N/0': 9,
          'Многоканальная система массового обслуживания с неограниченным ожиданием': 10,
          'Многоканальная система массового обслуживания с ожиданием и ограниченной длиной очереди': 10,
          'Задачи для самостоятельного решения 2': 12,
          }


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Dyuthi")
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 391, 711))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.listWidget.setFont(font)
        self.listWidget.setMouseTracking(False)
        self.listWidget.setTabletTracking(False)
        self.listWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setStyleSheet("QListWidget { border-style: outset; border-width: 1px }\n"
"QListWidget::item { border-bottom: 1px solid black }\n"
"QListWidget::item:selected { background-color: rgb(77, 148, 255) }\n"
"QListWidget::item:hover { background-color: rgb(153, 194, 255) }\n"
"")
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget.setLineWidth(5)
        self.listWidget.setMidLineWidth(0)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setBatchSize(100)
        self.listWidget.setWordWrap(True)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(389, -1, 891, 711))
        self.scrollArea.setStyleSheet("border-style: outset; border-width: 1px")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 875, 709))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(0, 0, 891, 711))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Теория телетрафика мультисервисных сетей"))
        self.listWidget.setSortingEnabled(False)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Простейший поток"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Суммирование и разъединение простейших потоков"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Показательный закон распределения времени обслуживания"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "Нестационарный Пуассоновский поток"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "Теорема Литтла"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "Задачи для самостоятельного решения 1"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "Одноканальная система массового обслуживания с отказами"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "Система массового обслуживания с ожиданием и без ограничения очереди"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "Система массового обслуживания с ожиданием и ограничением длины очереди"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "Многоканальная система массового обслуживания с отказами М/М/N/0"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "Многоканальная система массового обслуживания с неограниченным ожиданием"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "Многоканальная система массового обслуживания с ожиданием и ограниченной длиной очереди"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "Задачи для самостоятельного решения 2"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.listWidget.itemClicked.connect(self.qlistAction)

    def qlistAction(self, item):
        print(THEMES[item.text()])
        self.label.setPixmap(QtGui.QPixmap(f'img/{THEMES[item.text()]}.png'))
        self.label.resize(self.label.pixmap().height(), self.label.pixmap().height())


class mywindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(mywindow, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)


app = QtWidgets.QApplication([])
application = mywindow()
application.show()

sys.exit(app.exec())
